import { tool, type ToolDefinition } from "@opencode-ai/plugin"
import { writeFileSync, existsSync, readFileSync, readdirSync, statSync } from "fs"
import { join } from "path"

export const contextGeneratorTool: ToolDefinition = tool({
  description: "Auto-generate or update hierarchical context files (AGENTS.md, CLAUDE.md) throughout the project. These files provide critical grounding for AI agents.",
  args: {
    targetDir: tool.schema.string().optional(),
    force: tool.schema.boolean().optional(),
  },
  async execute(args, context) {
    const root = context.directory
    const target = args.targetDir ? join(root, args.targetDir) : root

    if (!existsSync(target)) {
      return `Error: Directory ${target} does not exist.`
    }

    const agentsMdPath = join(target, "AGENTS.md")
    if (existsSync(agentsMdPath) && !args.force) {
      return `AGENTS.md already exists in ${target}. Use force: true to overwrite.`
    }

    // Basic heuristic for project info
    const pkgPath = join(root, "package.json")
    let projectName = "Project"
    let techStack = "Unknown"
    if (existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"))
        projectName = pkg.name || projectName
        techStack = Object.keys(pkg.dependencies || {}).slice(0, 5).join(", ")
      } catch {}
    }

    const content = `# AGENTS.md for ${projectName}

## Context
- **Tech Stack**: ${techStack}
- **Primary Goal**: [Explain the main purpose of this directory/project]

## Rules for Agents
1. **Consistency**: Follow existing patterns in this directory.
2. **Safety**: Do not modify files in \`node_modules\` or other sensitive areas.
3. **Planning**: Always check \`.planning/STATE.md\` before executing major changes.

## Directory Map
${readdirSync(target).slice(0, 10).map(f => {
  const s = statSync(join(target, f))
  return `- \`${f}\`${s.isDirectory() ? "/" : ""} : [Description]`
}).join("\n")}

---
Generated by FlowDeck Context Generator.
`

    writeFileSync(agentsMdPath, content, "utf-8")
    return `Successfully generated AGENTS.md in ${target}.`
  },
})
